// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHRhyuBf9CiS7NTU8YjuOGIdDSkzgkXes',
    appId: '1:1026362298026:web:dc9be23c2335c99ff90ad3',
    messagingSenderId: '1026362298026',
    projectId: 'efreicsb2',
    authDomain: 'efreicsb2.firebaseapp.com',
    storageBucket: 'efreicsb2.firebasestorage.app',
    measurementId: 'G-BEH8PM9P5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyL1YA_b44uC5DBaQ2DN6-xgBxcbfV6AU',
    appId: '1:1026362298026:android:765ed59974c16636f90ad3',
    messagingSenderId: '1026362298026',
    projectId: 'efreicsb2',
    storageBucket: 'efreicsb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlovxhxKRigdP_yo9IqYezNbNbqmI8qwg',
    appId: '1:1026362298026:ios:9df8ddf569d77cd9f90ad3',
    messagingSenderId: '1026362298026',
    projectId: 'efreicsb2',
    storageBucket: 'efreicsb2.firebasestorage.app',
    iosBundleId: 'com.example.firstappg2Efrei2025',
  );
}
